//! Smoke tests for the happy path: simple structs, enums, and commands.

use crate::helpers::{assert_file_eq, run_generate_ok, Project};

const TYPES_HEADER: &str =
    "// This file was auto-generated by tauri-ts-generator\n// Do not edit this file manually\n";

#[test]
fn simple_struct_and_command() {
    let project = Project::with_source(
        r#"
        use serde::{Deserialize, Serialize};

        #[derive(Serialize, Deserialize)]
        pub struct User { pub id: i32, pub name: String }

        #[tauri::command]
        fn get_user(id: i32) -> Result<User, String> { todo!() }
        "#,
    );

    let output = run_generate_ok(&project);
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("Generated:"),
        "stdout missing status: {stdout}"
    );
    assert!(stdout.contains("Done!"));

    assert_file_eq(
        &project.types_out,
        &format!(
            "{TYPES_HEADER}\n\
            export interface User {{\n\
            \x20\x20id: number;\n\
            \x20\x20name: string;\n\
            }}\n"
        ),
    );

    assert_file_eq(
        &project.commands_out,
        &format!(
            "{TYPES_HEADER}\n\
            import {{ invoke }} from \"@tauri-apps/api/core\";\n\
            import type {{ User }} from \"./types\";\n\n\
            export async function getUser(id: number): Promise<User> {{\n\
            \x20\x20return invoke<User>(\"get_user\", {{ id }});\n\
            }}\n"
        ),
    );
}

#[test]
fn plain_enum_becomes_string_union() {
    let project = Project::with_source(
        r#"
        use serde::{Deserialize, Serialize};

        #[derive(Serialize, Deserialize)]
        pub enum Status { Active, Inactive, Pending }

        #[tauri::command]
        fn get_status() -> Result<Status, String> { todo!() }
        "#,
    );

    run_generate_ok(&project);
    let types = std::fs::read_to_string(&project.types_out).unwrap();
    assert!(
        types.contains(r#"export type Status ="#),
        "expected type alias for Status, got:\n{types}"
    );
    assert!(types.contains(r#""Active""#));
    assert!(types.contains(r#""Inactive""#));
    assert!(types.contains(r#""Pending""#));
}

#[test]
fn command_with_no_args_omits_payload_object() {
    let project = Project::with_source(
        r#"
        use serde::{Deserialize, Serialize};

        #[derive(Serialize, Deserialize)]
        pub struct Ping;

        #[tauri::command]
        fn ping() -> Result<Ping, String> { todo!() }
        "#,
    );

    run_generate_ok(&project);
    let commands = std::fs::read_to_string(&project.commands_out).unwrap();
    // No-arg commands should not pass a payload object to invoke.
    assert!(
        commands.contains(r#"invoke<Ping>("ping")"#),
        "expected no payload for zero-arg command, got:\n{commands}"
    );
}

#[test]
fn async_command_returns_promise_of_ok_type() {
    let project = Project::with_source(
        r#"
        use serde::{Deserialize, Serialize};

        #[derive(Serialize, Deserialize)]
        pub struct Data { pub value: String }

        #[tauri::command]
        async fn fetch() -> Result<Data, String> { todo!() }
        "#,
    );

    run_generate_ok(&project);
    let commands = std::fs::read_to_string(&project.commands_out).unwrap();
    assert!(commands.contains("Promise<Data>"));
}

#[test]
fn types_only_reachable_from_commands_are_emitted() {
    // `Orphan` is defined but never used by any command.
    let project = Project::with_source(
        r#"
        use serde::{Deserialize, Serialize};

        #[derive(Serialize, Deserialize)]
        pub struct Used { pub n: i32 }

        #[derive(Serialize, Deserialize)]
        pub struct Orphan { pub x: i32 }

        #[tauri::command]
        fn take(u: Used) -> Result<(), String> { todo!() }
        "#,
    );

    run_generate_ok(&project);
    let types = std::fs::read_to_string(&project.types_out).unwrap();
    assert!(types.contains("Used"));
    assert!(
        !types.contains("Orphan"),
        "Orphan is unreachable and should be excluded, got:\n{types}"
    );
}

#[test]
fn vec_option_hashmap_map_to_expected_ts() {
    let project = Project::with_source(
        r#"
        use serde::{Deserialize, Serialize};
        use std::collections::HashMap;

        #[derive(Serialize, Deserialize)]
        pub struct Doc {
            pub tags: Vec<String>,
            pub owner: Option<String>,
            pub meta: HashMap<String, i32>,
        }

        #[tauri::command]
        fn get_doc() -> Result<Doc, String> { todo!() }
        "#,
    );

    run_generate_ok(&project);
    let types = std::fs::read_to_string(&project.types_out).unwrap();
    assert!(types.contains("tags: string[]"), "Vec<String>:\n{types}");
    assert!(
        types.contains("owner: string | null"),
        "Option<String>:\n{types}"
    );
    assert!(
        types.contains("meta: Record<string, number>"),
        "HashMap<String,i32>:\n{types}"
    );
}
