// This file was auto-generated by tauri-codegen
// Do not edit this file manually

import { invoke } from "@tauri-apps/api/core";
import type { PodInfo, DeploymentInfo, ServiceInfo, ResourceStatus } from "./types";

export async function listPods(namespace: string | null): Promise<PodInfo[]> {
  return invoke<PodInfo[]>("list_pods", { namespace });
}

export async function getPod(name: string, namespace: string | null): Promise<PodInfo> {
  return invoke<PodInfo>("get_pod", { name, namespace });
}

export async function listDeployments(namespace: string | null): Promise<DeploymentInfo[]> {
  return invoke<DeploymentInfo[]>("list_deployments", { namespace });
}

export async function getService(name: string, namespace: string | null): Promise<ServiceInfo> {
  return invoke<ServiceInfo>("get_service", { name, namespace });
}

export async function getResourceStatus(name: string): Promise<ResourceStatus> {
  return invoke<ResourceStatus>("get_resource_status", { name });
}

