// This file was auto-generated by tauri-codegen
// Do not edit this file manually

export interface PodInfo {
  name: string;
  namespace: string;
  status: string;
  containers: ContainerInfo[];
}

export interface ContainerInfo {
  name: string;
  image: string;
  ready: boolean;
}

export interface DeploymentInfo {
  name: string;
  namespace: string;
  replicas: ReplicaInfo;
}

export interface ReplicaInfo {
  desired: number;
  ready: number;
  available: number;
}

export interface ServiceInfo {
  name: string;
  namespace: string;
  clusterIp: string | null;
}

export type ResourceStatus = "Running" | "Pending" | "Failed" | "Unknown";

