use crate::models::{CommandArg, RustType, TauriCommand};
use crate::utils::to_camel_case;
use std::collections::HashSet;
use std::path::Path;

use super::{type_mapper::rust_to_typescript, GeneratorContext};

/// Generate TypeScript commands file content
pub fn generate_commands_file(
    commands: &[TauriCommand],
    types_file_path: &Path,
    commands_file_path: &Path,
    ctx: &GeneratorContext,
) -> String {
    let mut output = String::new();

    // Add header comment
    output.push_str("// This file was auto-generated by tauri-ts-generator\n");
    output.push_str("// Do not edit this file manually\n\n");

    // Add Tauri import — include Channel when any command uses one
    if commands_use_channels(commands) {
        output.push_str("import { invoke, Channel } from \"@tauri-apps/api/core\";\n");
    } else {
        output.push_str("import { invoke } from \"@tauri-apps/api/core\";\n");
    }

    // Collect all custom types used in commands
    let used_types = collect_used_types(commands, ctx);

    if !used_types.is_empty() {
        // Calculate relative import path from commands file to types file
        let import_path = calculate_relative_import(types_file_path, commands_file_path);
        let mut types_list: Vec<_> = used_types.into_iter().collect();
        types_list.sort();
        output.push_str(&format!(
            "import type {{ {} }} from \"{}\";\n",
            types_list.join(", "),
            import_path
        ));
    }

    output.push('\n');

    // Generate function for each command
    for cmd in commands {
        output.push_str(&generate_command_function(cmd, ctx));
        output.push('\n');
    }

    output
}

/// Compute `(ts_alias_name, ts_inner_type)` pairs for all Channel args across
/// all commands. These are written as `export type Foo = Bar;` lines in types.ts.
///
/// Single-channel command `download(on_event: Channel<DownloadEvent>)`:
///   → `("downloadChannelType", "DownloadEvent")`
///
/// Multi-channel command `upload(on_progress: Channel<P>, on_done: Channel<D>)`:
///   → `("uploadOnProgressChannelType", "P")`, `("uploadOnDoneChannelType", "D")`
pub fn collect_channel_type_aliases(
    commands: &[TauriCommand],
    ctx: &GeneratorContext,
) -> Vec<(String, String)> {
    let mut aliases = Vec::new();

    for cmd in commands {
        let channel_args: Vec<_> = cmd
            .args
            .iter()
            .filter(|arg| matches!(&arg.ty, RustType::Channel(_)))
            .collect();

        if channel_args.is_empty() {
            continue;
        }

        let fn_name = crate::utils::to_camel_case(&cmd.name);

        if channel_args.len() == 1 {
            if let RustType::Channel(inner) = &channel_args[0].ty {
                aliases.push((
                    format!("{}ChannelType", fn_name),
                    rust_to_typescript(inner, ctx),
                ));
            }
        } else {
            for arg in &channel_args {
                if let RustType::Channel(inner) = &arg.ty {
                    let pascal_arg = crate::utils::to_pascal_case(&arg.name);
                    aliases.push((
                        format!("{}{}ChannelType", fn_name, pascal_arg),
                        rust_to_typescript(inner, ctx),
                    ));
                }
            }
        }
    }

    aliases
}

fn commands_use_channels(commands: &[TauriCommand]) -> bool {
    commands
        .iter()
        .any(|cmd| cmd.args.iter().any(|arg| type_uses_channel(&arg.ty)))
}

fn type_uses_channel(ty: &RustType) -> bool {
    match ty {
        RustType::Channel(_) => true,
        RustType::Vec(inner) | RustType::Option(inner) | RustType::Result(inner) => {
            type_uses_channel(inner)
        }
        RustType::HashMap { key, value } => type_uses_channel(key) || type_uses_channel(value),
        RustType::Tuple(types) => types.iter().any(type_uses_channel),
        _ => false,
    }
}

/// Collect all custom type names used in commands
fn collect_used_types(commands: &[TauriCommand], ctx: &GeneratorContext) -> HashSet<String> {
    let mut types = HashSet::new();

    for cmd in commands {
        // Check arguments
        for arg in &cmd.args {
            collect_types_from_rust_type(&arg.ty, ctx, &mut types);
        }

        // Check return type
        if let Some(ret_type) = &cmd.return_type {
            collect_types_from_rust_type(ret_type, ctx, &mut types);
        }
    }

    types
}

/// Collect custom type names from a RustType, filtered by the generator
/// context (only known-registered types count) and formatted with any
/// configured prefix/suffix.
///
/// A Rust field typed as `crate::types::User` surfaces here as the full
/// path string; the context registers types by simple name only, so we
/// reduce to the final segment before both membership check and formatting.
fn collect_types_from_rust_type(
    ty: &RustType,
    ctx: &GeneratorContext,
    types: &mut HashSet<String>,
) {
    crate::models::walk_custom_type_names(ty, &mut |name| {
        let simple = crate::utils::simple_name(name);
        if ctx.is_custom_type(simple) {
            types.insert(ctx.format_type_name(simple));
        }
    });
}

/// Generate a TypeScript function for a Tauri command
fn generate_command_function(cmd: &TauriCommand, ctx: &GeneratorContext) -> String {
    let mut output = String::new();

    // Function name in camelCase
    let fn_name = to_camel_case(&cmd.name);
    let fn_name = ctx.format_function_name(&fn_name);

    // Generate parameter list
    let params = generate_params(&cmd.args, ctx);

    // Generate return type
    let return_type = generate_return_type(&cmd.return_type, ctx);

    // Generate function signature
    output.push_str(&format!(
        "export async function {}({}): Promise<{}> {{\n",
        fn_name, params, return_type
    ));

    // Generate invoke call
    if cmd.args.is_empty() {
        output.push_str(&format!(
            "  return invoke<{}>(\"{}\");\n",
            return_type, cmd.name
        ));
    } else {
        let args_obj = generate_args_object(&cmd.args, cmd.rename_all.as_deref());
        output.push_str(&format!(
            "  return invoke<{}>(\"{}\", {{ {} }});\n",
            return_type, cmd.name, args_obj
        ));
    }

    output.push_str("}\n");

    output
}

/// Generate TypeScript parameter list
fn generate_params(args: &[CommandArg], ctx: &GeneratorContext) -> String {
    args.iter()
        .map(|arg| {
            let param_name = to_camel_case(&arg.name);
            let param_type = rust_to_typescript(&arg.ty, ctx);
            format!("{}: {}", param_name, param_type)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Generate TypeScript return type
fn generate_return_type(return_type: &Option<RustType>, ctx: &GeneratorContext) -> String {
    match return_type {
        Some(ty) => rust_to_typescript(ty, ctx),
        None => "void".to_string(),
    }
}

/// Generate the arguments object for invoke
///
/// By default, Tauri serializes command arguments to camelCase.
/// If `rename_all = "snake_case"` is specified, arguments stay as snake_case.
fn generate_args_object(args: &[CommandArg], rename_all: Option<&str>) -> String {
    let use_snake_case = rename_all == Some("snake_case");

    args.iter()
        .map(|arg| {
            let param_name = to_camel_case(&arg.name);

            if use_snake_case {
                // With rename_all = "snake_case", Tauri expects snake_case keys
                if arg.name == param_name {
                    // Already the same (e.g., single word like "id")
                    param_name
                } else {
                    // Map camelCase param to snake_case key
                    format!("{}: {}", arg.name, param_name)
                }
            } else {
                // Default: Tauri expects camelCase keys
                // Use shorthand since param name matches key name
                param_name
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Calculate relative import path from commands file to types file
fn calculate_relative_import(types_file: &Path, commands_file: &Path) -> String {
    // Get the directory of the commands file
    let commands_dir = commands_file.parent().unwrap_or(Path::new("."));
    let types_dir = types_file.parent().unwrap_or(Path::new("."));
    let types_name = types_file.file_stem().unwrap_or_default().to_string_lossy();

    // If same directory, just use ./filename
    if commands_dir == types_dir {
        return format!("./{}", types_name);
    }

    // Try to strip prefix (types_file is inside commands_dir)
    if let Ok(relative) = types_file.strip_prefix(commands_dir) {
        let path = relative.with_extension("");
        let path_str = path.to_string_lossy();
        if path_str.starts_with('.') {
            return path_str.to_string();
        } else {
            return format!("./{}", path_str);
        }
    }

    // Compute relative path by finding common ancestor
    let commands_components: Vec<_> = commands_dir.components().collect();
    let types_components: Vec<_> = types_dir.components().collect();

    // Find common prefix length
    let common_len = commands_components
        .iter()
        .zip(types_components.iter())
        .take_while(|(a, b)| a == b)
        .count();

    // Calculate how many ".." we need to go up from commands_dir
    let up_count = commands_components.len() - common_len;

    // Build the path: ../../../path/to/types_file
    let mut result = String::new();

    if up_count == 0 {
        result.push_str("./");
    } else {
        for _ in 0..up_count {
            result.push_str("../");
        }
    }

    // Add remaining path components from types file
    for component in types_components.iter().skip(common_len) {
        result.push_str(&component.as_os_str().to_string_lossy());
        result.push('/');
    }

    // Add the filename without extension
    result.push_str(&types_name);

    // Clean up trailing slash if needed
    result.trim_end_matches('/').to_string()
}

#[cfg(test)]
mod tests;
