/// Generate helpers.ts content — emitted whenever any command uses a Channel arg.
pub fn generate_helpers_file() -> String {
    let mut output = String::new();
    output.push_str("// This file was auto-generated by tauri-ts-generator\n");
    output.push_str("// Do not edit this file manually\n\n");
    output.push_str("import { Channel } from \"@tauri-apps/api/core\";\n\n");
    output.push_str(
        "export function getChannelFor<T>(onMessage?: (message: T) => void): Channel<T> {\n",
    );
    output.push_str("  const channel = new Channel<T>();\n");
    output.push_str("  if (onMessage) channel.onmessage = onMessage;\n");
    output.push_str("  return channel;\n");
    output.push_str("}\n");
    output
}
