use crate::models::{EnumRepresentation, RustEnum, RustStruct, RustTypeAlias, VariantData};

use super::{type_mapper::rust_to_typescript, GeneratorContext};

/// Generate TypeScript types file content
pub fn generate_types_file(
    structs: &[RustStruct],
    enums: &[RustEnum],
    aliases: &[RustTypeAlias],
    ctx: &GeneratorContext,
) -> String {
    let mut output = String::new();

    // Add header comment
    output.push_str("// This file was auto-generated by tauri-ts-generator\n");
    output.push_str("// Do not edit this file manually\n\n");

    // Generate interfaces for structs
    for s in structs {
        output.push_str(&generate_interface(s, ctx));
        output.push('\n');
    }

    // Generate types for enums
    for e in enums {
        output.push_str(&generate_enum_type(e, ctx));
        output.push('\n');
    }

    // Generate type aliases
    for alias in aliases {
        output.push_str(&generate_alias_type(alias, ctx));
        output.push('\n');
    }

    output
}

/// Render a single struct field to TypeScript format (name, optional marker, type)
fn render_field(
    field: &crate::models::StructField,
    ctx: &GeneratorContext,
) -> (String, &'static str, String) {
    // If use_optional is true and type is Option<T>, generate field?: T instead of field: T | null
    let (optional_marker, ts_type) = if field.use_optional {
        if let crate::models::RustType::Option(inner) = &field.ty {
            ("?", rust_to_typescript(inner, ctx))
        } else {
            ("", rust_to_typescript(&field.ty, ctx))
        }
    } else {
        ("", rust_to_typescript(&field.ty, ctx))
    };

    // Field name already reflects serde configuration from parser
    // (rename, rename_all, or original name if no serde attrs)
    let field_name = field.name.clone();

    (field_name, optional_marker, ts_type)
}

/// Generate a TypeScript interface from a Rust struct
/// If the struct has #[serde(flatten)] fields, generate a type alias with intersection
fn generate_interface(s: &RustStruct, ctx: &GeneratorContext) -> String {
    let mut output = String::new();

    let interface_name = ctx.format_type_name(&s.name);

    // Add generic parameters if present
    let generics_str = if s.generics.is_empty() {
        String::new()
    } else {
        format!("<{}>", s.generics.join(", "))
    };

    // Separate normal fields from flattened fields
    let (flatten_fields, normal_fields): (Vec<_>, Vec<_>) =
        s.fields.iter().partition(|f| f.is_flatten);

    if flatten_fields.is_empty() {
        // No flatten fields - generate regular interface
        output.push_str(&format!(
            "export interface {}{} {{\n",
            interface_name, generics_str
        ));

        for field in &s.fields {
            let (field_name, optional_marker, ts_type) = render_field(field, ctx);
            output.push_str(&format!(
                "  {}{}: {};\n",
                field_name, optional_marker, ts_type
            ));
        }

        output.push_str("}\n");
    } else {
        // Has flatten fields - generate type alias with intersection
        output.push_str(&format!(
            "export type {}{} = ",
            interface_name, generics_str
        ));

        // Generate inline object for normal fields
        if normal_fields.is_empty() {
            // No normal fields, start with first flatten type
            let mut flatten_types: Vec<String> = flatten_fields
                .iter()
                .map(|f| rust_to_typescript(&f.ty, ctx))
                .collect();
            output.push_str(&flatten_types.remove(0));
            for ft in flatten_types {
                output.push_str(&format!(" & {}", ft));
            }
        } else {
            // Generate inline object for normal fields
            output.push_str("{\n");
            for field in normal_fields {
                let (field_name, optional_marker, ts_type) = render_field(field, ctx);
                output.push_str(&format!(
                    "  {}{}: {};\n",
                    field_name, optional_marker, ts_type
                ));
            }
            output.push('}');

            // Add intersection with flatten types
            for field in flatten_fields {
                let ts_type = rust_to_typescript(&field.ty, ctx);
                output.push_str(&format!(" & {}", ts_type));
            }
        }

        output.push_str(";\n");
    }

    output
}

/// Generate a TypeScript type from a Rust enum
fn generate_enum_type(e: &RustEnum, ctx: &GeneratorContext) -> String {
    let mut output = String::new();

    let type_name = ctx.format_type_name(&e.name);

    // Add generic parameters if present
    let generics_str = if e.generics.is_empty() {
        String::new()
    } else {
        format!("<{}>", e.generics.join(", "))
    };

    let variants: Vec<String> = e
        .variants
        .iter()
        .map(|variant| generate_variant(variant, &e.representation, ctx))
        .collect();

    if variants.is_empty() {
        output.push_str(&format!(
            "export type {}{} = never;\n",
            type_name, generics_str
        ));
    } else {
        output.push_str(&format!(
            "export type {}{} =\n  | {};\n",
            type_name,
            generics_str,
            variants.join("\n  | ")
        ));
    }

    output
}

fn generate_variant(
    variant: &crate::models::EnumVariant,
    representation: &EnumRepresentation,
    ctx: &GeneratorContext,
) -> String {
    match representation {
        EnumRepresentation::External => match &variant.data {
            VariantData::Unit => format!("\"{}\"", variant.name),
            VariantData::Tuple(types) => {
                let ts_types: Vec<_> = types.iter().map(|t| rust_to_typescript(t, ctx)).collect();
                let inner = if ts_types.len() == 1 {
                    ts_types[0].clone()
                } else {
                    format!("[{}]", ts_types.join(", "))
                };
                format!("{{ {}: {} }}", variant.name, inner)
            }
            VariantData::Struct(fields) => {
                let inner = generate_struct_body(fields, ctx);
                format!("{{ {}: {} }}", variant.name, inner)
            }
        },
        EnumRepresentation::Internal { tag } => {
            match &variant.data {
                VariantData::Unit => format!("{{ {}: \"{}\" }}", tag, variant.name),
                VariantData::Struct(fields) => {
                    let mut body = generate_struct_body(fields, ctx);
                    // Remove opening brace and insert tag
                    body.remove(0); // remove '{'
                    format!("{{ {}: \"{}\",{}", tag, variant.name, body)
                }
                VariantData::Tuple(types) => {
                    // Serde's internal tagging doesn't support tuple variants (it errors at runtime).
                    // However, if it's a newtype (single element), we can try to handle it.
                    // Emit a warning and generate a best-effort type.
                    if types.len() == 1 {
                        // Newtype variant - could potentially work if inner type is a struct
                        eprintln!(
                            "Warning: Internal tagging with newtype variant '{}' may not work \
                            correctly with serde. Consider using adjacent tagging instead.",
                            variant.name
                        );
                        let inner_ts = rust_to_typescript(&types[0], ctx);
                        // Generate: { tag: "Name" } & InnerType
                        format!("({{ {}: \"{}\" }} & {})", tag, variant.name, inner_ts)
                    } else {
                        eprintln!(
                            "Warning: Internal tagging does not support tuple variants with \
                            multiple elements (variant '{}'). Serde will error at runtime. \
                            Consider using external or adjacent tagging instead.",
                            variant.name
                        );
                        // Fall back to just the tag since this won't work in serde anyway
                        format!("{{ {}: \"{}\" }}", tag, variant.name)
                    }
                }
            }
        }
        EnumRepresentation::Adjacent { tag, content } => match &variant.data {
            VariantData::Unit => format!("{{ {}: \"{}\" }}", tag, variant.name),
            VariantData::Tuple(types) => {
                let ts_types: Vec<_> = types.iter().map(|t| rust_to_typescript(t, ctx)).collect();
                let inner = if ts_types.len() == 1 {
                    ts_types[0].clone()
                } else {
                    format!("[{}]", ts_types.join(", "))
                };
                format!(
                    "{{ {}: \"{}\"; {}: {} }}",
                    tag, variant.name, content, inner
                )
            }
            VariantData::Struct(fields) => {
                let inner = generate_struct_body(fields, ctx);
                format!(
                    "{{ {}: \"{}\"; {}: {} }}",
                    tag, variant.name, content, inner
                )
            }
        },
        EnumRepresentation::Untagged => match &variant.data {
            VariantData::Unit => "null".to_string(), // Untagged unit matches null? Or nothing? Serde says it errors if it can't match. Usually untagged is for matching shapes.
            VariantData::Tuple(types) => {
                let ts_types: Vec<_> = types.iter().map(|t| rust_to_typescript(t, ctx)).collect();
                if ts_types.len() == 1 {
                    ts_types[0].clone()
                } else {
                    format!("[{}]", ts_types.join(", "))
                }
            }
            VariantData::Struct(fields) => generate_struct_body(fields, ctx),
        },
    }
}

/// Generate a TypeScript type alias from a Rust type alias
fn generate_alias_type(alias: &RustTypeAlias, ctx: &GeneratorContext) -> String {
    let alias_name = ctx.format_type_name(&alias.name);

    let generics_str = if alias.generics.is_empty() {
        String::new()
    } else {
        format!("<{}>", alias.generics.join(", "))
    };

    let target_ts = rust_to_typescript(&alias.target, ctx);

    format!(
        "export type {}{} = {};\n",
        alias_name, generics_str, target_ts
    )
}

fn generate_struct_body(fields: &[crate::models::StructField], ctx: &GeneratorContext) -> String {
    let params: Vec<String> = fields
        .iter()
        .map(|field| {
            let (field_name, optional_marker, ts_type) = render_field(field, ctx);
            format!("{}{}: {}", field_name, optional_marker, ts_type)
        })
        .collect();
    format!("{{ {} }}", params.join("; "))
}

#[cfg(test)]
mod tests;
