//! Pipeline module - orchestrates the code generation process
//!
//! Flow: Scan -> Parse -> Resolve -> Collect -> Generate

pub mod collect;

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

use crate::cargo_expand::{find_cargo_manifest, run_cargo_expand};
use crate::config::Config;
use crate::diagnostics::Diagnostics;
use crate::generator::{
    commands_gen::generate_commands_file, types_gen::generate_types_file, GeneratorContext,
};
use crate::known_types;
use crate::models::{ParseResult, RustEnum, RustStruct, RustType, RustTypeAlias};
use crate::parser::{parse_commands, parse_types_expanded_with_aliases, ParsedTypes};
use crate::resolver::ModuleResolver;
use crate::scanner::Scanner;

pub use collect::TypeCollectionResult;

/// Main pipeline for code generation
pub struct Pipeline {
    diag: Diagnostics,
}

impl Pipeline {
    pub fn new(verbose: bool) -> Self {
        Self {
            diag: Diagnostics::new(verbose),
        }
    }

    /// Run the full generation pipeline
    pub fn run(&self, config: &Config) -> Result<()> {
        self.diag.debug(format!(
            "Scanning directory: {}",
            config.input.source_dir.display()
        ));

        // Step 1: Scan for Rust files
        let rust_files = self.scan_files(config)?;

        self.diag
            .debug(format!("Found {} Rust files", rust_files.len()));

        // Step 1.5: Optionally run cargo expand for macro-generated types
        let expanded_code = if config.input.use_cargo_expand {
            self.run_cargo_expand(config)?
        } else {
            None
        };

        // Step 2: Parse all files and build resolver
        let (mut parse_result, resolver, expanded_types) =
            self.parse_files(&rust_files, config, expanded_code.as_deref())?;

        // Step 2.5: Filter out Tauri special types (State, Window, etc.) including aliases
        self.filter_tauri_special_args(&mut parse_result.commands, &resolver);

        // Step 3: Collect and resolve types used in commands
        let type_collection = self.collect_reachable_types(
            &parse_result.commands,
            &resolver,
            expanded_types.as_ref(),
        );

        // Step 4: Check for conflicts
        if !type_collection.conflicts.is_empty() {
            self.diag.error("Type name conflicts detected:");
            for (type_name, files) in &type_collection.conflicts {
                self.diag.error(format!(
                    "  Type '{}' is used from multiple sources:",
                    type_name
                ));
                for file in files {
                    self.diag.error(format!("    - {}", file.display()));
                }
            }
            anyhow::bail!(
                "Found {} type name conflict(s). Please rename types or use explicit imports to avoid ambiguity.",
                type_collection.conflicts.len()
            );
        }

        // Step 4.5: Warn about unresolved types (likely macro-generated)
        if !type_collection.unresolved.is_empty() {
            self.diag.warn(format!(
                "{} type(s) could not be resolved and will not be generated:",
                type_collection.unresolved.len()
            ));
            for (type_name, used_in) in &type_collection.unresolved {
                self.diag.warn(format!(
                    "  - '{}' (used in {})",
                    type_name,
                    used_in.display()
                ));
            }
            if !config.input.use_cargo_expand {
                self.diag.info("");
                self.diag.info(
                    "Hint: These types may be generated by macros (e.g., progenitor, serde, etc.).",
                );
                self.diag
                    .info("      To include macro-generated types, add to your config:");
                self.diag.info("        [input]");
                self.diag.info("        use_cargo_expand = true");
                self.diag.info("");
            }
        }

        // Summary
        self.diag.info(format!(
            "Parsed {} commands, {} structs (used), {} enums (used), {} aliases (used)",
            parse_result.commands.len(),
            type_collection.structs.len(),
            type_collection.enums.len(),
            type_collection.aliases.len()
        ));

        // Step 6: Generate TypeScript files
        self.generate_output(
            config,
            &parse_result,
            &type_collection.structs,
            &type_collection.enums,
            &type_collection.aliases,
        )?;

        self.diag.info("Done!");

        Ok(())
    }

    /// Step 1: Scan for Rust files
    fn scan_files(&self, config: &Config) -> Result<Vec<PathBuf>> {
        let scanner = Scanner::new(
            config.input.source_dir.clone(),
            config.input.exclude.clone(),
        );
        scanner.scan()
    }

    /// Step 1.5: Run cargo expand if enabled
    fn run_cargo_expand(&self, config: &Config) -> Result<Option<String>> {
        self.diag
            .warn("cargo expand is enabled. This will compile the project and may take a while.");
        self.diag.warn(
            "This is used to extract macro-generated types (e.g., from progenitor, serde, etc.)",
        );

        // Find cargo manifest
        let manifest_path = config
            .input
            .cargo_manifest
            .clone()
            .or_else(|| find_cargo_manifest(&config.input.source_dir));

        let manifest_path = match manifest_path {
            Some(p) => p,
            None => {
                self.diag
                    .warn("Could not find Cargo.toml for cargo expand. Skipping macro expansion.");
                return Ok(None);
            }
        };

        self.diag
            .debug(format!("Using Cargo.toml at: {}", manifest_path.display()));

        // Run cargo expand
        let result = run_cargo_expand(&manifest_path)?;

        // Print all warnings (from cargo-expand itself — already formatted)
        for warning in &result.warnings {
            eprintln!("{}", warning);
        }

        if result.code.is_empty() {
            self.diag
                .warn("cargo expand produced no output. Continuing with regular parsing.");
            Ok(None)
        } else {
            Ok(Some(result.code))
        }
    }

    /// Step 2: Parse all files and build module resolver
    fn parse_files(
        &self,
        rust_files: &[PathBuf],
        config: &Config,
        expanded_code: Option<&str>,
    ) -> Result<(ParseResult, ModuleResolver, Option<ParsedTypes>)> {
        let mut resolver = ModuleResolver::new();
        let base_path = config.input.source_dir.clone();
        let mut parse_result = ParseResult::new();

        // Store expanded types temporarily - we'll register them AFTER parsing source files
        let mut expanded_types: Option<ParsedTypes> = None;

        // If we have expanded code, parse types from it (but don't register yet)
        if let Some(code) = expanded_code {
            let expanded_path = PathBuf::from("<cargo-expand>");

            match parse_types_expanded_with_aliases(code, &expanded_path) {
                Ok(parsed) => {
                    self.diag.debug(format!(
                        "Found {} structs, {} enums, {} aliases from cargo expand",
                        parsed.structs.len(),
                        parsed.enums.len(),
                        parsed.aliases.len()
                    ));

                    expanded_types = Some(parsed);
                }
                Err(e) => {
                    self.diag.warn(format!(
                        "Failed to parse types from cargo expand output: {}",
                        e
                    ));
                }
            }
        }

        // First, parse all source files - this registers types in the resolver
        for file_path in rust_files {
            let content = fs::read_to_string(file_path)
                .with_context(|| format!("Failed to read file: {}", file_path.display()))?;

            // Build resolver scope for this file
            if let Err(e) = resolver.parse_file(file_path, &content, &base_path) {
                self.diag.debug(format!(
                    "Failed to parse imports in {}: {}",
                    file_path.display(),
                    e
                ));
            }

            // Parse commands
            match parse_commands(&content, file_path) {
                Ok(commands) => {
                    if !commands.is_empty() {
                        self.diag.debug(format!(
                            "Found {} commands in {}",
                            commands.len(),
                            file_path.display()
                        ));
                    }
                    parse_result.commands.extend(commands);
                }
                Err(e) => {
                    self.diag.warn(format!(
                        "Failed to parse commands in {}: {}",
                        file_path.display(),
                        e
                    ));
                }
            }
        }

        // Now register cargo-expand types, but ONLY if they don't already exist in source files.
        // This prevents the "ambiguous type" bug while still allowing macro-generated types
        // (that don't exist in source) to be resolved.
        if let Some(parsed) = &expanded_types {
            let expanded_path = PathBuf::from("<cargo-expand>");

            for s in &parsed.structs {
                resolver.register_expanded_type_if_missing(&s.name, &expanded_path);
            }
            for e in &parsed.enums {
                resolver.register_expanded_type_if_missing(&e.name, &expanded_path);
            }
            for alias in &parsed.aliases {
                resolver.register_expanded_type_if_missing(&alias.name, &expanded_path);
            }
        }

        Ok((parse_result, resolver, expanded_types))
    }

    /// Step 3: Collect types reachable from command signatures.
    /// Thin wrapper over `pipeline::collect::collect_reachable_types` kept so
    /// the existing `Pipeline::collect_reachable_types(...)` test call sites
    /// continue to work unchanged.
    pub(crate) fn collect_reachable_types(
        &self,
        commands: &[crate::models::TauriCommand],
        resolver: &ModuleResolver,
        expanded_types: Option<&ParsedTypes>,
    ) -> TypeCollectionResult {
        collect::collect_reachable_types(commands, resolver, expanded_types, &self.diag)
    }

    /// Step 6: Generate TypeScript output files
    fn generate_output(
        &self,
        config: &Config,
        parse_result: &ParseResult,
        filtered_structs: &[RustStruct],
        filtered_enums: &[RustEnum],
        aliases: &[RustTypeAlias],
    ) -> Result<()> {
        // Ensure output directories exist before writing files
        config.ensure_output_directories()?;

        // Create generator context
        let mut ctx = GeneratorContext::new(config.naming.clone());

        for s in filtered_structs {
            ctx.register_type(&s.name);
        }
        for e in filtered_enums {
            ctx.register_type(&e.name);
        }
        for alias in aliases {
            ctx.register_type(&alias.name);
        }

        // Generate types.ts
        let types_content = generate_types_file(filtered_structs, filtered_enums, aliases, &ctx);

        fs::write(&config.output.types_file, &types_content).with_context(|| {
            format!(
                "Failed to write types file: {}",
                config.output.types_file.display()
            )
        })?;

        self.diag
            .info(format!("Generated: {}", config.output.types_file.display()));

        // Generate commands.ts
        let commands_content = generate_commands_file(
            &parse_result.commands,
            &config.output.types_file,
            &config.output.commands_file,
            &ctx,
        );

        fs::write(&config.output.commands_file, &commands_content).with_context(|| {
            format!(
                "Failed to write commands file: {}",
                config.output.commands_file.display()
            )
        })?;

        self.diag.info(format!(
            "Generated: {}",
            config.output.commands_file.display()
        ));

        Ok(())
    }

    /// Step 2.5: Filter out Tauri special types from command arguments
    /// This handles both direct uses (State<T>) and type aliases (type MyState = State<T>)
    fn filter_tauri_special_args(
        &self,
        commands: &mut [crate::models::TauriCommand],
        resolver: &ModuleResolver,
    ) {
        for cmd in commands.iter_mut() {
            cmd.args.retain(|arg| {
                // Get the base type name from the RustType
                let type_name = match &arg.ty {
                    RustType::Custom(name) => {
                        // Extract just the type name (without path)
                        name.split("::").last().unwrap_or(name).to_string()
                    }
                    RustType::Unknown(name) => name.split("::").last().unwrap_or(name).to_string(),
                    _ => return true, // Keep primitives, Vec, Option, etc.
                };

                // Check if it's directly a Tauri special type
                if known_types::is_tauri_special_type(&type_name) {
                    return false;
                }

                // Check if it's an alias to a Tauri special type
                if let Some(target) = resolver.resolve_alias_target(&type_name, &cmd.source_file) {
                    if known_types::is_tauri_special_type(&target) {
                        return false;
                    }
                }

                true
            });
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{walk_custom_type_names, CommandArg, TauriCommand};
    use std::collections::HashSet;

    fn test_path() -> PathBuf {
        PathBuf::from("test.rs")
    }

    /// Test-local wrapper that exercises the shared model walker.
    fn collect_custom_types_from_rust_type(ty: &RustType) -> Vec<String> {
        let mut set: HashSet<String> = HashSet::new();
        walk_custom_type_names(ty, &mut |n| {
            set.insert(n.to_string());
        });
        let mut out: Vec<String> = set.into_iter().collect();
        out.sort();
        out
    }

    #[test]
    fn test_collect_custom_types_simple() {
        let ty = RustType::Custom("User".to_string());
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["User"]);
    }

    #[test]
    fn test_collect_custom_types_primitive() {
        let ty = RustType::Primitive("String".to_string());
        let types = collect_custom_types_from_rust_type(&ty);
        assert!(types.is_empty());
    }

    #[test]
    fn test_collect_custom_types_vec() {
        let ty = RustType::Vec(Box::new(RustType::Custom("Item".to_string())));
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["Item"]);
    }

    #[test]
    fn test_collect_custom_types_option() {
        let ty = RustType::Option(Box::new(RustType::Custom("User".to_string())));
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["User"]);
    }

    #[test]
    fn test_collect_custom_types_result() {
        let ty = RustType::Result(Box::new(RustType::Custom("Response".to_string())));
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["Response"]);
    }

    #[test]
    fn test_collect_custom_types_hashmap() {
        let ty = RustType::HashMap {
            key: Box::new(RustType::Primitive("String".to_string())),
            value: Box::new(RustType::Custom("User".to_string())),
        };
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["User"]);
    }

    #[test]
    fn test_collect_custom_types_tuple() {
        let ty = RustType::Tuple(vec![
            RustType::Custom("User".to_string()),
            RustType::Custom("Item".to_string()),
            RustType::Primitive("i32".to_string()),
        ]);
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["Item", "User"]);
    }

    #[test]
    fn test_collect_custom_types_nested() {
        let ty = RustType::Vec(Box::new(RustType::Option(Box::new(RustType::Custom(
            "User".to_string(),
        )))));
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["User"]);
    }

    #[test]
    fn test_collect_custom_types_no_duplicates() {
        let ty = RustType::Tuple(vec![
            RustType::Custom("User".to_string()),
            RustType::Custom("User".to_string()),
        ]);
        let types = collect_custom_types_from_rust_type(&ty);
        assert_eq!(types, vec!["User"]);
    }

    fn write_file(path: &std::path::Path, content: &str) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, content).unwrap();
    }

    #[test]
    fn test_collect_reachable_types_from_commands() {
        let pipeline = Pipeline::new(false);
        let temp_dir = tempfile::tempdir().unwrap();
        let src_dir = temp_dir.path().join("src");

        let types_path = src_dir.join("types.rs");
        let types_code = r#"
            pub struct Request { pub data: String }
            pub struct Response { pub result: i32 }
        "#;
        write_file(&types_path, types_code);

        let mut resolver = ModuleResolver::new();
        resolver
            .parse_file(&types_path, types_code, &src_dir)
            .unwrap();

        let commands = vec![TauriCommand {
            name: "process".to_string(),
            args: vec![CommandArg {
                name: "req".to_string(),
                ty: RustType::Custom("Request".to_string()),
            }],
            return_type: Some(RustType::Custom("Response".to_string())),
            source_file: types_path.clone(),
            rename_all: None,
        }];

        let result = pipeline.collect_reachable_types(&commands, &resolver, None);

        assert!(result.conflicts.is_empty());
        assert!(result.structs.iter().any(|s| s.name == "Request"));
        assert!(result.structs.iter().any(|s| s.name == "Response"));
    }

    #[test]
    fn test_collect_reachable_types_includes_aliases() {
        let pipeline = Pipeline::new(false);
        let temp_dir = tempfile::tempdir().unwrap();
        let src_dir = temp_dir.path().join("src");

        let types_path = src_dir.join("types.rs");
        let types_code = r#"
            pub struct User { pub id: i32 }
            pub type UserAlias = User;
        "#;
        write_file(&types_path, types_code);

        let mut resolver = ModuleResolver::new();
        resolver
            .parse_file(&types_path, types_code, &src_dir)
            .unwrap();

        let commands = vec![TauriCommand {
            name: "get_user".to_string(),
            args: vec![CommandArg {
                name: "user".to_string(),
                ty: RustType::Custom("UserAlias".to_string()),
            }],
            return_type: None,
            source_file: types_path.clone(),
            rename_all: None,
        }];

        let result = pipeline.collect_reachable_types(&commands, &resolver, None);

        assert!(result.aliases.iter().any(|a| a.name == "UserAlias"));
        assert!(result.structs.iter().any(|s| s.name == "User"));
    }

    #[test]
    fn test_collect_reachable_types_detects_conflicts() {
        let pipeline = Pipeline::new(false);
        let temp_dir = tempfile::tempdir().unwrap();
        let src_dir = temp_dir.path().join("src");

        let a_path = src_dir.join("a.rs");
        let b_path = src_dir.join("b.rs");
        let cmd_path = src_dir.join("commands.rs");
        let code_a = "pub struct User { pub id: i32 }";
        let code_b = "pub struct User { pub name: String }";
        let cmd_code = "fn some_fn() {}";

        write_file(&a_path, code_a);
        write_file(&b_path, code_b);
        write_file(&cmd_path, cmd_code);

        let mut resolver = ModuleResolver::new();
        resolver.parse_file(&a_path, code_a, &src_dir).unwrap();
        resolver.parse_file(&b_path, code_b, &src_dir).unwrap();
        resolver.parse_file(&cmd_path, cmd_code, &src_dir).unwrap();

        let commands = vec![TauriCommand {
            name: "get_user".to_string(),
            args: vec![],
            return_type: Some(RustType::Custom("User".to_string())),
            source_file: cmd_path,
            rename_all: None,
        }];

        let result = pipeline.collect_reachable_types(&commands, &resolver, None);

        assert!(result.conflicts.contains_key("User"));
    }

    #[test]
    fn test_pipeline_verbose_mode() {
        assert!(Pipeline::new(true).diag.verbose());
        assert!(!Pipeline::new(false).diag.verbose());
    }

    #[test]
    fn test_filter_tauri_special_types() {
        let pipeline = Pipeline::new(false);
        let resolver = ModuleResolver::new();

        // Create a command with special Tauri types
        let mut commands = vec![TauriCommand {
            name: "test_command".to_string(),
            args: vec![
                CommandArg {
                    name: "state".to_string(),
                    ty: RustType::Custom("State".to_string()),
                },
                CommandArg {
                    name: "window".to_string(),
                    ty: RustType::Custom("Window".to_string()),
                },
                CommandArg {
                    name: "id".to_string(),
                    ty: RustType::Primitive("i32".to_string()),
                },
            ],
            return_type: None,
            source_file: test_path(),
            rename_all: None,
        }];

        pipeline.filter_tauri_special_args(&mut commands, &resolver);

        // State and Window should be filtered out
        assert_eq!(commands[0].args.len(), 1);
        assert_eq!(commands[0].args[0].name, "id");
    }

    #[test]
    fn test_filter_tauri_app_handle() {
        let pipeline = Pipeline::new(false);
        let resolver = ModuleResolver::new();

        let mut commands = vec![TauriCommand {
            name: "with_app".to_string(),
            args: vec![
                CommandArg {
                    name: "app".to_string(),
                    ty: RustType::Custom("AppHandle".to_string()),
                },
                CommandArg {
                    name: "data".to_string(),
                    ty: RustType::Primitive("String".to_string()),
                },
            ],
            return_type: None,
            source_file: test_path(),
            rename_all: None,
        }];

        pipeline.filter_tauri_special_args(&mut commands, &resolver);

        // AppHandle should be filtered out
        assert_eq!(commands[0].args.len(), 1);
        assert_eq!(commands[0].args[0].name, "data");
    }

    #[test]
    fn test_filter_tauri_special_types_via_alias() {
        let pipeline = Pipeline::new(false);
        let mut resolver = ModuleResolver::new();

        // Register a type alias: type MyState = State<AppState>
        let code = "pub type MyState<'a> = State<'a, AppState>;";
        let path = test_path();
        resolver
            .parse_file(&path, code, &PathBuf::from("."))
            .unwrap();

        let mut commands = vec![TauriCommand {
            name: "aliased_command".to_string(),
            args: vec![
                CommandArg {
                    name: "state".to_string(),
                    ty: RustType::Custom("MyState".to_string()),
                },
                CommandArg {
                    name: "id".to_string(),
                    ty: RustType::Primitive("i32".to_string()),
                },
            ],
            return_type: None,
            source_file: path.clone(),
            rename_all: None,
        }];

        pipeline.filter_tauri_special_args(&mut commands, &resolver);

        // MyState (alias to State) should be filtered out
        assert_eq!(commands[0].args.len(), 1);
        assert_eq!(commands[0].args[0].name, "id");
    }

    #[test]
    fn test_collect_reachable_types_handles_self_referential_struct() {
        // A self-referential tree node is the canonical stress test for the
        // reachable-type fixpoint loop: without dedup, this would recurse forever.
        let pipeline = Pipeline::new(false);
        let temp_dir = tempfile::tempdir().unwrap();
        let src_dir = temp_dir.path().join("src");

        let types_path = src_dir.join("types.rs");
        let types_code = r#"
            pub struct Node {
                pub value: i32,
                pub next: Option<Box<Node>>,
            }
        "#;
        write_file(&types_path, types_code);

        let mut resolver = ModuleResolver::new();
        resolver
            .parse_file(&types_path, types_code, &src_dir)
            .unwrap();

        let commands = vec![TauriCommand {
            name: "get_head".to_string(),
            args: vec![],
            return_type: Some(RustType::Custom("Node".to_string())),
            source_file: types_path.clone(),
            rename_all: None,
        }];

        let result = pipeline.collect_reachable_types(&commands, &resolver, None);

        assert!(result.conflicts.is_empty());
        // Node must appear exactly once despite the self-reference.
        let node_count = result.structs.iter().filter(|s| s.name == "Node").count();
        assert_eq!(node_count, 1, "Self-referential struct must be deduped");
    }

    #[test]
    fn test_collect_reachable_types_handles_mutually_recursive_structs() {
        // A -> B -> A cycle. Without cycle protection the fixpoint loop
        // would oscillate between the two types forever.
        let pipeline = Pipeline::new(false);
        let temp_dir = tempfile::tempdir().unwrap();
        let src_dir = temp_dir.path().join("src");

        let types_path = src_dir.join("types.rs");
        let types_code = r#"
            pub struct A { pub b: Option<Box<B>> }
            pub struct B { pub a: Option<Box<A>> }
        "#;
        write_file(&types_path, types_code);

        let mut resolver = ModuleResolver::new();
        resolver
            .parse_file(&types_path, types_code, &src_dir)
            .unwrap();

        let commands = vec![TauriCommand {
            name: "get_a".to_string(),
            args: vec![],
            return_type: Some(RustType::Custom("A".to_string())),
            source_file: types_path.clone(),
            rename_all: None,
        }];

        let result = pipeline.collect_reachable_types(&commands, &resolver, None);

        assert_eq!(result.structs.iter().filter(|s| s.name == "A").count(), 1);
        assert_eq!(result.structs.iter().filter(|s| s.name == "B").count(), 1);
    }
}
