//! Pipeline module - orchestrates the code generation process
//!
//! Flow: Scan -> Parse -> Resolve -> Collect -> Generate

pub mod collect;

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

use crate::cargo_expand::{find_cargo_manifest, run_cargo_expand};
use crate::config::Config;
use crate::diagnostics::Diagnostics;
use crate::generator::{
    commands_gen::generate_commands_file, types_gen::generate_types_file, GeneratorContext,
};
use crate::known_types;
use crate::models::{ParseResult, RustEnum, RustStruct, RustType, RustTypeAlias};
use crate::parser::{parse_commands, parse_types, ParseOptions, ParsedTypes};
use crate::resolver::ModuleResolver;
use crate::scanner::Scanner;

pub use collect::TypeCollectionResult;

/// Main pipeline for code generation
pub struct Pipeline {
    diag: Diagnostics,
}

impl Pipeline {
    pub fn new(verbose: bool) -> Self {
        Self {
            diag: Diagnostics::new(verbose),
        }
    }

    /// Run the full generation pipeline
    pub fn run(&self, config: &Config) -> Result<()> {
        // Install the ambient Diagnostics sink for any helper that can't
        // easily take a `&Diagnostics` parameter (the serde-attr walkers,
        // the type-mapper's Unknown fallbacks, etc.).
        crate::diagnostics::install(self.diag);

        self.diag.debug(format!(
            "Scanning directory: {}",
            config.input.source_dir.display()
        ));

        // Step 1: Scan for Rust files
        let rust_files = self.scan_files(config)?;

        self.diag
            .debug(format!("Found {} Rust files", rust_files.len()));

        // Step 1.5: Optionally run cargo expand for macro-generated types
        let expanded_code = if config.input.use_cargo_expand {
            self.run_cargo_expand(config)?
        } else {
            None
        };

        // Step 2: Parse all files and build resolver
        let (mut parse_result, resolver, expanded_types) =
            self.parse_files(&rust_files, config, expanded_code.as_deref())?;

        // Step 2.5: Filter out Tauri special types (State, Window, etc.) including aliases
        self.filter_tauri_special_args(&mut parse_result.commands, &resolver);

        // Step 2.6: Detect two `#[tauri::command]` functions with the same
        // name. JavaScript callers do `invoke("name", …)` — if two commands
        // share a name the generated TS would define the function twice and
        // the Rust backend only ever routes to one of them. Fail loudly.
        self.check_duplicate_command_names(&parse_result.commands)?;

        // Step 3: Collect and resolve types used in commands
        let type_collection = collect::collect_reachable_types(
            &parse_result.commands,
            &resolver,
            expanded_types.as_ref(),
            &self.diag,
        );

        // Step 4: Check for conflicts
        if !type_collection.conflicts.is_empty() {
            self.diag.error("Type name conflicts detected:");
            for (type_name, files) in &type_collection.conflicts {
                self.diag.error(format!(
                    "  Type '{}' is used from multiple sources:",
                    type_name
                ));
                for file in files {
                    self.diag.error(format!("    - {}", file.display()));
                }
            }
            anyhow::bail!(
                "Found {} type name conflict(s). Please rename types or use explicit imports to avoid ambiguity.",
                type_collection.conflicts.len()
            );
        }

        // Step 4.5: Warn about unresolved types (likely macro-generated)
        if !type_collection.unresolved.is_empty() {
            self.diag.warn(format!(
                "{} type(s) could not be resolved and will not be generated:",
                type_collection.unresolved.len()
            ));
            for (type_name, used_in) in &type_collection.unresolved {
                self.diag.warn(format!(
                    "  - '{}' (used in {})",
                    type_name,
                    used_in.display()
                ));
            }
            if !config.input.use_cargo_expand {
                self.diag.info("");
                self.diag.info(
                    "Hint: These types may be generated by macros (e.g., progenitor, serde, etc.).",
                );
                self.diag
                    .info("      To include macro-generated types, add to your config:");
                self.diag.info("        [input]");
                self.diag.info("        use_cargo_expand = true");
                self.diag.info("");
            }
        }

        // Summary
        self.diag.info(format!(
            "Parsed {} commands, {} structs (used), {} enums (used), {} aliases (used)",
            parse_result.commands.len(),
            type_collection.structs.len(),
            type_collection.enums.len(),
            type_collection.aliases.len()
        ));

        // Step 6: Generate TypeScript files
        self.generate_output(
            config,
            &parse_result,
            &type_collection.structs,
            &type_collection.enums,
            &type_collection.aliases,
        )?;

        self.diag.info("Done!");

        Ok(())
    }

    /// Step 1: Scan for Rust files
    fn scan_files(&self, config: &Config) -> Result<Vec<PathBuf>> {
        let scanner = Scanner::new(
            config.input.source_dir.clone(),
            config.input.exclude.clone(),
        );
        scanner.scan()
    }

    /// Step 1.5: Run cargo expand if enabled
    fn run_cargo_expand(&self, config: &Config) -> Result<Option<String>> {
        self.diag
            .warn("cargo expand is enabled. This will compile the project and may take a while.");
        self.diag.warn(
            "This is used to extract macro-generated types (e.g., from progenitor, serde, etc.)",
        );

        // Find cargo manifest
        let manifest_path = config
            .input
            .cargo_manifest
            .clone()
            .or_else(|| find_cargo_manifest(&config.input.source_dir));

        let manifest_path = match manifest_path {
            Some(p) => p,
            None => {
                self.diag
                    .warn("Could not find Cargo.toml for cargo expand. Skipping macro expansion.");
                return Ok(None);
            }
        };

        self.diag
            .debug(format!("Using Cargo.toml at: {}", manifest_path.display()));

        // Run cargo expand
        let result = run_cargo_expand(&manifest_path)?;

        // Print all warnings (from cargo-expand itself — already formatted)
        for warning in &result.warnings {
            eprintln!("{}", warning);
        }

        if result.code.is_empty() {
            self.diag
                .warn("cargo expand produced no output. Continuing with regular parsing.");
            Ok(None)
        } else {
            Ok(Some(result.code))
        }
    }

    /// Step 2: Parse all files and build module resolver
    fn parse_files(
        &self,
        rust_files: &[PathBuf],
        config: &Config,
        expanded_code: Option<&str>,
    ) -> Result<(ParseResult, ModuleResolver, Option<ParsedTypes>)> {
        let mut resolver = ModuleResolver::new();
        let base_path = config.input.source_dir.clone();
        let mut parse_result = ParseResult::new();

        // Store expanded types temporarily - we'll register them AFTER parsing source files
        let mut expanded_types: Option<ParsedTypes> = None;

        // If we have expanded code, parse types from it (but don't register yet)
        if let Some(code) = expanded_code {
            let expanded_path = PathBuf::from("<cargo-expand>");

            match parse_types(code, &expanded_path, ParseOptions::EXPANDED_ALL) {
                Ok(parsed) => {
                    self.diag.debug(format!(
                        "Found {} structs, {} enums, {} aliases from cargo expand",
                        parsed.structs.len(),
                        parsed.enums.len(),
                        parsed.aliases.len()
                    ));

                    expanded_types = Some(parsed);
                }
                Err(e) => {
                    self.diag.warn(format!(
                        "Failed to parse types from cargo expand output: {}",
                        e
                    ));
                }
            }
        }

        // First, parse all source files - this registers types in the resolver
        for file_path in rust_files {
            let content = fs::read_to_string(file_path)
                .with_context(|| format!("Failed to read file: {}", file_path.display()))?;

            // Build resolver scope for this file
            if let Err(e) = resolver.parse_file(file_path, &content, &base_path) {
                self.diag.debug(format!(
                    "Failed to parse imports in {}: {}",
                    file_path.display(),
                    e
                ));
            }

            // Parse commands
            match parse_commands(&content, file_path) {
                Ok(commands) => {
                    if !commands.is_empty() {
                        self.diag.debug(format!(
                            "Found {} commands in {}",
                            commands.len(),
                            file_path.display()
                        ));
                    }
                    parse_result.commands.extend(commands);
                }
                Err(e) => {
                    self.diag.warn(format!(
                        "Failed to parse commands in {}: {}",
                        file_path.display(),
                        e
                    ));
                }
            }
        }

        // Now register cargo-expand types, but ONLY if they don't already exist in source files.
        // This prevents the "ambiguous type" bug while still allowing macro-generated types
        // (that don't exist in source) to be resolved.
        if let Some(parsed) = &expanded_types {
            let expanded_path = PathBuf::from("<cargo-expand>");

            for s in &parsed.structs {
                resolver.register_expanded_type_if_missing(&s.name, &expanded_path);
            }
            for e in &parsed.enums {
                resolver.register_expanded_type_if_missing(&e.name, &expanded_path);
            }
            for alias in &parsed.aliases {
                resolver.register_expanded_type_if_missing(&alias.name, &expanded_path);
            }
        }

        Ok((parse_result, resolver, expanded_types))
    }

    /// Step 6: Generate TypeScript output files
    fn generate_output(
        &self,
        config: &Config,
        parse_result: &ParseResult,
        filtered_structs: &[RustStruct],
        filtered_enums: &[RustEnum],
        aliases: &[RustTypeAlias],
    ) -> Result<()> {
        // Ensure output directories exist before writing files
        config.ensure_output_directories()?;

        // Create generator context
        let mut ctx = GeneratorContext::new(config.naming.clone());

        for s in filtered_structs {
            ctx.register_type(&s.name);
        }
        for e in filtered_enums {
            ctx.register_enum(&e.name);
        }
        for alias in aliases {
            ctx.register_type(&alias.name);
        }

        // Generate types.ts
        let types_content = generate_types_file(filtered_structs, filtered_enums, aliases, &ctx);

        fs::write(&config.output.types_file, &types_content).with_context(|| {
            format!(
                "Failed to write types file: {}",
                config.output.types_file.display()
            )
        })?;

        self.diag
            .info(format!("Generated: {}", config.output.types_file.display()));

        // Generate commands.ts
        let commands_content = generate_commands_file(
            &parse_result.commands,
            &config.output.types_file,
            &config.output.commands_file,
            &ctx,
        );

        fs::write(&config.output.commands_file, &commands_content).with_context(|| {
            format!(
                "Failed to write commands file: {}",
                config.output.commands_file.display()
            )
        })?;

        self.diag.info(format!(
            "Generated: {}",
            config.output.commands_file.display()
        ));

        Ok(())
    }

    /// Step 2.6: detect duplicate `#[tauri::command]` names across the
    /// project. Reports every colliding source file pair-wise so the user
    /// can find them without re-scanning the tree by hand.
    fn check_duplicate_command_names(
        &self,
        commands: &[crate::models::TauriCommand],
    ) -> Result<()> {
        use std::collections::HashMap;

        let mut by_name: HashMap<&str, Vec<&std::path::Path>> = HashMap::new();
        for cmd in commands {
            by_name
                .entry(cmd.name.as_str())
                .or_default()
                .push(cmd.source_file.as_path());
        }

        let duplicates: Vec<_> = by_name
            .iter()
            .filter(|(_, files)| files.len() > 1)
            .collect();

        if duplicates.is_empty() {
            return Ok(());
        }

        self.diag
            .error("Duplicate #[tauri::command] names detected:");
        for (name, files) in &duplicates {
            self.diag
                .error(format!("  '{}' is defined in {} files:", name, files.len()));
            for file in *files {
                self.diag.error(format!("    - {}", file.display()));
            }
        }
        anyhow::bail!(
            "Found {} duplicate command name(s). Rename the Rust functions or use `#[tauri::command(rename = \"...\")]` to give them distinct invoke names.",
            duplicates.len()
        );
    }

    /// Step 2.5: Filter out Tauri special types from command arguments
    /// This handles both direct uses (State<T>) and type aliases (type MyState = State<T>)
    fn filter_tauri_special_args(
        &self,
        commands: &mut [crate::models::TauriCommand],
        resolver: &ModuleResolver,
    ) {
        for cmd in commands.iter_mut() {
            cmd.args.retain(|arg| {
                // Get the base type name from the RustType
                let type_name = match &arg.ty {
                    RustType::Custom { name, .. } => crate::utils::simple_name(name).to_string(),
                    RustType::Unknown(name) => crate::utils::simple_name(name).to_string(),
                    _ => return true, // Keep primitives, Vec, Option, etc.
                };

                // Check if it's directly a Tauri special type
                if known_types::is_tauri_special_type(&type_name) {
                    return false;
                }

                // Check if it's an alias to a Tauri special type
                if let Some(target) = resolver.resolve_alias_target(&type_name, &cmd.source_file) {
                    if known_types::is_tauri_special_type(&target) {
                        return false;
                    }
                }

                true
            });
        }
    }
}

#[cfg(test)]
mod tests;
